# Generated by Django 5.2.7 on 2025-10-25 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_favoritelist_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorite_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='favorites.favoritelist'),
        ),
    ]
